### PR TITLE
Chapter 7. Complex Loops

### PR DESCRIPTION
**Pull request by HouseBreaker**
The entire chapter has been translated, including the web application, which is now implemented using Flask.

### CODE REVIEW

**Review by vncpetrov — CHANGES_REQUESTED** [review]
Blurred images should be fixed: 15.Fruits-16.png, 15.Fruits-13.png

**Comment by vncpetrov** [comment]
Image **15.Fruits-13.png** is still blurred

**Review by miglen — APPROVED** [review]
Прегледах промените в текста и според мен са ОК.

**Comment by HouseBreaker** [comment]
I resized fruits-13.png again. It's larger than the 600px recommended by the wiki, but this way, no definition is lost. The original image in the C# book is 1800px wide and look fine; I assume images should be scaled appropriately by GitBook.

**Pull request merged**
